name: Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
{{#if_eq packageManagerName "pnpm"}}
      # pnpm action uses the packageManager field in package.json to
      # understand which version to install.
      - uses: pnpm/action-setup@v2
{{/if_eq}}
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: '{{ packageManagerName }}'
      - name: Install dependencies
        run: {{ packageManagerInstallCmd }}
      - name: Build plugin
        run: {{ packageManagerName }} run build
      - name: Get metadata
        id: metadata
        run: |
          sudo apt-get install jq tr
          export GRAFANA_PLUGIN_DEPENDENCY=$(cat dist/plugin.json | jq -r | tr -d '<>=~^')
          echo "plugin-dependency=${GRAFANA_PLUGIN_DEPENDENCY}" >> $GITHUB_OUTPUT
          
      - name: Compatibility check latest
        run: npx @grafana/levitate@latest is-compatible --path src/module.ts --target @grafana/data,@grafana/ui,@grafana/runtime

      - name: Compatibility check minimum
        run: npx @grafana/levitate@latest is-compatible --path src/module.ts --target @grafana/data@{{ steps.metadata.outputs.plugin-dependency }},@grafana/ui@{{ steps.metadata.outputs.plugin-dependency }},@grafana/runtime@{{ steps.metadata.outputs.plugin-dependency }}
